//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Abnormal
    {
        public int ID { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public System.Guid AbnormalUuid { get; set; }
        public string Name { get; set; }
        public string Sex { get; set; }
        public string StuNum { get; set; }
        public Nullable<System.Guid> CollegeUuid { get; set; }
        public Nullable<System.Guid> MajorUuid { get; set; }
        public Nullable<System.Guid> StuClassUuid { get; set; }
        public Nullable<System.DateTime> AbnormalTime { get; set; }
        public Nullable<int> IsDeleted { get; set; }
        public string AddTime { get; set; }
        public string AddPeople { get; set; }
        public Nullable<System.Guid> SchoolDistrictUuid { get; set; }
        public string State { get; set; }
        public string WarnState { get; set; }
    
        public virtual College College { get; set; }
        public virtual Major Major { get; set; }
        public virtual SchoolDistrict SchoolDistrict { get; set; }
        public virtual StuClass StuClass { get; set; }
    }
}
