//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Curriculum
    {
        public int ID { get; set; }
        public System.Guid CurriculumUuid { get; set; }
        public string CurriculumName { get; set; }
        public Nullable<System.Guid> WeeklyUuid { get; set; }
        public Nullable<System.Guid> FestivalUuid { get; set; }
        public string Week { get; set; }
        public string CurriculumNum { get; set; }
        public string Weekly { get; set; }
        public string Festival { get; set; }
        public string SchoolYear { get; set; }
        public string Semester { get; set; }
    }
}
