//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dc_EarlyWarningRecord
    {
        public int ID { get; set; }
        public string RoomID { get; set; }
        public string RoomName { get; set; }
        public string AddTime { get; set; }
        public string Reason { get; set; }
        public string Remarks { get; set; }
        public string State { get; set; }
        public string IsDelete { get; set; }
        public string DeleteTime { get; set; }
    }
}
