//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dc_TemHum
    {
        public int ID { get; set; }
        public string InstrumentID { get; set; }
        public string Temperature { get; set; }
        public string Humidity { get; set; }
        public string State { get; set; }
        public string InCharge { get; set; }
        public string InChargeID { get; set; }
        public string IsDelete { get; set; }
        public string AddTime { get; set; }
        public string InstrumentName { get; set; }
        public string DeleteTime { get; set; }
        public string RoomID { get; set; }
        public string RoomName { get; set; }
    }
}
