//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary1
{
    using System;
    using System.Collections.Generic;
    
    public partial class HazardousChemicalsWarehouse
    {
        public int ID { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public System.Guid HazardousChemicalsWarehouseUuid { get; set; }
        public string HazardousChemicalsWarehouseName { get; set; }
        public string HazardousChemicalsWarehouseBasicInformation { get; set; }
        public string BuildingName { get; set; }
        public string RoomNumber { get; set; }
        public string Principal { get; set; }
        public string Phone { get; set; }
        public string AllowEntry { get; set; }
        public Nullable<int> IsDeleted { get; set; }
        public string AddTime { get; set; }
        public string AddPeople { get; set; }
    }
}
