//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary1
{
    using System;
    using System.Collections.Generic;
    
    public partial class RecyclingManagement
    {
        public int ID { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public System.Guid RecyclingManagementUuid { get; set; }
        public string RecyclingManagementTagUuid { get; set; }
        public string RecyclingManagementName { get; set; }
        public string RecyclingManagementPeople { get; set; }
        public Nullable<System.DateTime> RecyclingManagementTime { get; set; }
        public string Mark { get; set; }
        public Nullable<int> IsDeleted { get; set; }
        public string AddTime { get; set; }
        public string AddPeople { get; set; }
    }
}
