//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary1
{
    using System;
    using System.Collections.Generic;
    
    public partial class ScoreAdd
    {
        public int ID { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public System.Guid ScoreAddUuid { get; set; }
        public Nullable<System.Guid> DepartmentUuid { get; set; }
        public string DepartmentScore { get; set; }
        public string DepartmentPicture { get; set; }
        public string DepartmentPoints { get; set; }
        public string DepartmentAddPoints { get; set; }
        public Nullable<int> IsDeleted { get; set; }
        public string AddTime { get; set; }
        public string AddPeople { get; set; }
        public Nullable<int> ScoreType { get; set; }
        public string EventsPoints { get; set; }
    
        public virtual Department Department { get; set; }
    }
}
