//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student
    {
        public int ID { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public System.Guid StudentUuid { get; set; }
        public string Name { get; set; }
        public string Sex { get; set; }
        public string StuNum { get; set; }
        public Nullable<System.Guid> CollegeUuid { get; set; }
        public Nullable<System.Guid> MajorUuid { get; set; }
        public Nullable<System.Guid> StuClassUuid { get; set; }
        public string YiCard { get; set; }
        public Nullable<System.Guid> DormitoryUuid { get; set; }
        public string Picture { get; set; }
        public Nullable<System.Guid> DormitoryNumUuid { get; set; }
        public string Phone { get; set; }
        public string IdCard { get; set; }
        public string Email { get; set; }
        public string Nation { get; set; }
        public string Political { get; set; }
        public string Religion { get; set; }
        public Nullable<int> IsDeleted { get; set; }
        public string AddTime { get; set; }
        public string AddPeople { get; set; }
        public Nullable<System.Guid> SchoolDistrictUuid { get; set; }
    
        public virtual College College { get; set; }
        public virtual Dormitory Dormitory { get; set; }
        public virtual DormitoryNum DormitoryNum { get; set; }
        public virtual Major Major { get; set; }
        public virtual SchoolDistrict SchoolDistrict { get; set; }
        public virtual StuClass StuClass { get; set; }
    }
}
