//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary1
{
    using System;
    using System.Collections.Generic;
    
    public partial class sys_InstrumentUse
    {
        public int ID { get; set; }
        public System.Guid sys_InstrumentUseUuid { get; set; }
        public string ApparatusName { get; set; }
        public string Worker { get; set; }
        public string AddTime { get; set; }
        public string AddPeople { get; set; }
        public string stime { get; set; }
        public string etime { get; set; }
        public string setime { get; set; }
        public string TheLength { get; set; }
        public string intro { get; set; }
        public string Money { get; set; }
    }
}
