//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary1
{
    using System;
    using System.Collections.Generic;
    
    public partial class sys_BlackList
    {
        public int ID { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public System.Guid sys_BlackListUuid { get; set; }
        public string UserName { get; set; }
        public string AddTime { get; set; }
        public string AddPeople { get; set; }
        public string EndTime { get; set; }
        public string Reason { get; set; }
        public string Type { get; set; }
        public string EquipmentName { get; set; }
        public string YuyueType { get; set; }
        public string Comment { get; set; }
        public string number { get; set; }
        public string phone { get; set; }
        public string Eamil { get; set; }
        public string card { get; set; }
    }
}
