//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary1
{
    using System;
    using System.Collections.Generic;
    
    public partial class sys_Instrument
    {
        public int id { get; set; }
        public System.Guid sys_InstrumentUuid { get; set; }
        public Nullable<System.Guid> sys_InstrumentTypeUuid { get; set; }
        public string bianhao { get; set; }
        public string studentNo { get; set; }
        public string iname { get; set; }
        public string guige { get; set; }
        public Nullable<System.DateTime> time { get; set; }
        public string canjia { get; set; }
        public Nullable<double> count { get; set; }
        public Nullable<decimal> price { get; set; }
        public string gonplace { get; set; }
        public string photo { get; set; }
        public string lab { get; set; }
        public string roonnumber { get; set; }
        public string guanPeopleID { get; set; }
        public string detail { get; set; }
        public string img { get; set; }
        public string imgtwo { get; set; }
        public string imgstr { get; set; }
        public string imgfor { get; set; }
        public Nullable<decimal> money { get; set; }
        public string appartus { get; set; }
        public string isshow { get; set; }
        public string makestate { get; set; }
        public Nullable<int> labId { get; set; }
        public string instrupower { get; set; }
        public string guanPeopleName { get; set; }
        public string EntranceGuaerdID { get; set; }
        public string EntranceGuaerdName { get; set; }
        public string ismanagement { get; set; }
        public string menttype { get; set; }
        public string smalltime { get; set; }
        public string minprice { get; set; }
        public string remark { get; set; }
        public string Isoptional { get; set; }
        public string Dispark { get; set; }
    }
}
