//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary1
{
    using System;
    using System.Collections.Generic;
    
    public partial class sys_LaboratoryLog
    {
        public int id { get; set; }
        public System.Guid sys_LaboratoryLogUuid { get; set; }
        public Nullable<int> roomid { get; set; }
        public string username { get; set; }
        public string state { get; set; }
        public Nullable<int> classid { get; set; }
        public string demo { get; set; }
        public string classstate { get; set; }
        public string proquestion { get; set; }
        public string prostate { get; set; }
        public string laboquestion { get; set; }
        public string labostate { get; set; }
        public Nullable<System.DateTime> applytime { get; set; }
    }
}
