//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary1
{
    using System;
    using System.Collections.Generic;
    
    public partial class sys_User
    {
        public int id { get; set; }
        public System.Guid sys_UserUuid { get; set; }
        public string username { get; set; }
        public string userpassword { get; set; }
        public Nullable<int> roleid { get; set; }
        public string photo { get; set; }
        public Nullable<System.DateTime> lasttime { get; set; }
        public string linestate { get; set; }
        public string truename { get; set; }
        public Nullable<System.DateTime> ActiveTime { get; set; }
        public string mobile { get; set; }
        public string email { get; set; }
        public string sex { get; set; }
        public string CardNumber { get; set; }
        public string LearnWorkNumber { get; set; }
        public string PersonnelType { get; set; }
        public string ReviewStatus { get; set; }
        public string isaudite { get; set; }
        public string adddress { get; set; }
        public string job { get; set; }
        public string department { get; set; }
        public string AdmissionTime { get; set; }
        public string ClassName { get; set; }
        public string DateBirth { get; set; }
        public Nullable<System.DateTime> dataAddTime { get; set; }
        public string PupilName { get; set; }
        public string Iccid { get; set; }
        public string Remark { get; set; }
        public string phone { get; set; }
    }
}
