//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary1
{
    using System;
    using System.Collections.Generic;
    
    public partial class sys_InsOpen
    {
        public int id { get; set; }
        public System.Guid sys_InsOpenUuid { get; set; }
        public string name { get; set; }
        public string week { get; set; }
        public string kstime { get; set; }
        public string sjtime { get; set; }
        public string Isoptional { get; set; }
        public string BeginTime { get; set; }
        public string EndTime { get; set; }
        public string IsDel { get; set; }
        public Nullable<System.Guid> sys_InstrumentUuid { get; set; }
        public string Dispark { get; set; }
    }
}
