//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary1
{
    using System;
    using System.Collections.Generic;
    
    public partial class sys_ApparatusRegistration
    {
        public int id { get; set; }
        public System.Guid sys_ApparatusRegistrationUuid { get; set; }
        public string isbig { get; set; }
        public string name { get; set; }
        public Nullable<System.Guid> sys_InstrumentUuid { get; set; }
        public Nullable<int> num { get; set; }
        public string isaudit { get; set; }
        public string isback { get; set; }
        public string money { get; set; }
        public string size { get; set; }
        public string isusetime { get; set; }
        public string usetype { get; set; }
        public string rooomid { get; set; }
        public Nullable<System.DateTime> stime { get; set; }
        public Nullable<System.DateTime> etime { get; set; }
        public string applicationnameid { get; set; }
        public string applicationpurpose { get; set; }
        public string consumablesnum { get; set; }
        public string consumablesname { get; set; }
        public string laboratory { get; set; }
        public Nullable<int> sampleid { get; set; }
        public string note { get; set; }
        public string auditreason { get; set; }
        public string auditername { get; set; }
        public string taskname { get; set; }
        public string taskresourse { get; set; }
        public string cardnumber { get; set; }
        public string usertimes { get; set; }
        public string isteacher { get; set; }
        public Nullable<System.DateTime> applytime { get; set; }
        public Nullable<System.Guid> sys_LaboratoryUuid { get; set; }
        public Nullable<int> xinhao { get; set; }
        public Nullable<int> enable { get; set; }
        public string teacheraudit { get; set; }
        public string auditperson { get; set; }
        public Nullable<System.DateTime> sstime { get; set; }
        public Nullable<System.DateTime> setime { get; set; }
        public string types { get; set; }
        public string stimes { get; set; }
        public string truename { get; set; }
        public string capital { get; set; }
        public string ExperimentPurpose { get; set; }
        public string ExperimentalScheme { get; set; }
        public string FileState { get; set; }
        public string ArchivalAudit { get; set; }
        public string FileResult { get; set; }
        public Nullable<System.DateTime> FileNoTime { get; set; }
        public Nullable<System.DateTime> FileGoTime { get; set; }
        public string JianMianMoney { get; set; }
        public string AddMoney { get; set; }
        public string Isxsf { get; set; }
        public string SXCLShiJi { get; set; }
        public string QiTi { get; set; }
        public string GuangBan { get; set; }
        public string Isxhx { get; set; }
        public string HXName { get; set; }
        public string ProbjetName { get; set; }
        public string ProbjetLaiYuan { get; set; }
        public string CeShiContent { get; set; }
        public string NiCStime { get; set; }
        public string NiCSCount { get; set; }
        public string Issfsy { get; set; }
        public string SQDanWei { get; set; }
        public string NumberSample { get; set; }
        public string ActualCost { get; set; }
        public string Isdelete { get; set; }
        public string phone { get; set; }
    }
}
