//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary1
{
    using System;
    using System.Collections.Generic;
    
    public partial class sys_InstrumentFault
    {
        public int ID { get; set; }
        public System.Guid sys_InstrumentFaultUuid { get; set; }
        public Nullable<System.Guid> sys_InstrumentUuid { get; set; }
        public string Reason { get; set; }
        public string AddTime { get; set; }
        public string AddPeople { get; set; }
        public string OccurrenceTime { get; set; }
    }
}
