//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary1
{
    using System;
    using System.Collections.Generic;
    
    public partial class sys_Laboratory
    {
        public int id { get; set; }
        public System.Guid sys_LaboratoryUuid { get; set; }
        public string roomid { get; set; }
        public string roomname { get; set; }
        public string roomarea { get; set; }
        public string chief { get; set; }
        public Nullable<int> pronumber { get; set; }
        public string hasprojection { get; set; }
        public Nullable<int> facnumber { get; set; }
        public string category { get; set; }
        public string photo { get; set; }
        public string phototwo { get; set; }
        public string photostr { get; set; }
        public string photofor { get; set; }
        public string detail { get; set; }
        public string isshow { get; set; }
        public string makestate { get; set; }
    }
}
