//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary1
{
    using System;
    using System.Collections.Generic;
    
    public partial class SystemIcon
    {
        public System.Guid SystemIconUUID { get; set; }
        public string Code { get; set; }
        public string Size { get; set; }
        public string Color { get; set; }
        public string Custom { get; set; }
        public string Description { get; set; }
        public int Status { get; set; }
        public int IsDeleted { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public System.Guid CreatedByUserGuid { get; set; }
        public string CreatedByUserName { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public Nullable<System.Guid> ModifiedByUserGuid { get; set; }
        public string ModifiedByUserName { get; set; }
        public int ID { get; set; }
    }
}
