//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary1
{
    using System;
    using System.Collections.Generic;
    
    public partial class SystemUser
    {
        public System.Guid SystemUserUUID { get; set; }
        public string LoginName { get; set; }
        public string RealName { get; set; }
        public string UserIdCard { get; set; }
        public string PassWord { get; set; }
        public Nullable<int> UserType { get; set; }
        public Nullable<System.Guid> SchoolUUID { get; set; }
        public string AddTime { get; set; }
        public string AddPeople { get; set; }
        public Nullable<int> IsDeleted { get; set; }
        public string ManageDepartment { get; set; }
        public int ID { get; set; }
        public string ZaiGang { get; set; }
        public string Phone { get; set; }
        public string Email { get; set; }
        public string Sex { get; set; }
        public string InTime { get; set; }
        public string Types { get; set; }
        public string Address { get; set; }
        public string SystemRoleUUid { get; set; }
        public string Remarks { get; set; }
        public string StaffNum { get; set; }
        public string Wechat { get; set; }
        public string Topic { get; set; }
        public string Content { get; set; }
        public string Train { get; set; }
        public string Main { get; set; }
        public string Job { get; set; }
        public Nullable<int> HealthCertificate { get; set; }
        public Nullable<int> IsStaff { get; set; }
        public Nullable<int> IsCreEdu { get; set; }
        public string PersonnelType { get; set; }
        public string ReviewStatus { get; set; }
        public string CardNumber { get; set; }
        public string IsBlacklist { get; set; }
    }
}
