//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary1
{
    using System;
    using System.Collections.Generic;
    
    public partial class SystemMenu
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SystemMenu()
        {
            this.SystemPermissions = new HashSet<SystemPermission>();
        }
    
        public System.Guid SystemMenuUUID { get; set; }
        public string Name { get; set; }
        public string Url { get; set; }
        public string Alias { get; set; }
        public string Icon { get; set; }
        public Nullable<System.Guid> ParentGuid { get; set; }
        public string ParentName { get; set; }
        public Nullable<int> Level { get; set; }
        public string Description { get; set; }
        public Nullable<int> Sort { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<int> IsDeleted { get; set; }
        public Nullable<int> IsDefaultRouter { get; set; }
        public string CreatedOn { get; set; }
        public Nullable<System.Guid> CreatedByUserGuid { get; set; }
        public string CreatedByUserName { get; set; }
        public string ModifiedOn { get; set; }
        public Nullable<System.Guid> ModifiedByUserGuid { get; set; }
        public string ModifiedByUserName { get; set; }
        public string Component { get; set; }
        public Nullable<int> HideInMenu { get; set; }
        public Nullable<int> NotCache { get; set; }
        public string BeforeCloseFun { get; set; }
        public int ID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SystemPermission> SystemPermissions { get; set; }
    }
}
