//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Weekly
    {
        public int ID { get; set; }
        public System.Guid WeeklyUuid { get; set; }
        public string SchoolYear { get; set; }
        public string Semester { get; set; }
        public string WeeklyName { get; set; }
        public string WeeklyTime { get; set; }
    }
}
