//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary1
{
    using System;
    using System.Collections.Generic;
    
    public partial class whp_EntramceGuard
    {
        public int id { get; set; }
        public System.Guid whp_EntramceGuardUuid { get; set; }
        public string GNameListID { get; set; }
        public string Entcardnumber { get; set; }
        public string ip { get; set; }
        public Nullable<int> USB { get; set; }
        public string stime { get; set; }
        public string etime { get; set; }
        public string GNameListName { get; set; }
        public string StudenListID { get; set; }
        public string StudentListName { get; set; }
        public string EntcardType { get; set; }
        public int IsDelete { get; set; }
        public System.DateTime AddTime { get; set; }
        public string AddPeople { get; set; }
    }
}
