//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary1
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class yixueyuanEntities : DbContext
    {
        public yixueyuanEntities()
            : base("name=yixueyuanEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Abnormal> Abnormals { get; set; }
        public virtual DbSet<AccessControlRecord> AccessControlRecords { get; set; }
        public virtual DbSet<AnjianType> AnjianTypes { get; set; }
        public virtual DbSet<ApartmentRecord> ApartmentRecords { get; set; }
        public virtual DbSet<ApartmentWarn> ApartmentWarns { get; set; }
        public virtual DbSet<Blacker> Blackers { get; set; }
        public virtual DbSet<CampusPatrol> CampusPatrols { get; set; }
        public virtual DbSet<Car> Cars { get; set; }
        public virtual DbSet<CarAccident> CarAccidents { get; set; }
        public virtual DbSet<CarBlack> CarBlacks { get; set; }
        public virtual DbSet<CarIllegalStop> CarIllegalStops { get; set; }
        public virtual DbSet<CarNonMotor> CarNonMotors { get; set; }
        public virtual DbSet<CarNonMotorAccident> CarNonMotorAccidents { get; set; }
        public virtual DbSet<CarNonMotorBlack> CarNonMotorBlacks { get; set; }
        public virtual DbSet<CarNonMotorHelmeted> CarNonMotorHelmeteds { get; set; }
        public virtual DbSet<CarNonMotorIllegalStop> CarNonMotorIllegalStops { get; set; }
        public virtual DbSet<CarNonMotorManned> CarNonMotorManneds { get; set; }
        public virtual DbSet<CarNonMotorSpeedRecord> CarNonMotorSpeedRecords { get; set; }
        public virtual DbSet<CarSpeedRecord> CarSpeedRecords { get; set; }
        public virtual DbSet<College> Colleges { get; set; }
        public virtual DbSet<Curriculum> Curricula { get; set; }
        public virtual DbSet<Dc_EarlyWarningRecord> Dc_EarlyWarningRecord { get; set; }
        public virtual DbSet<Dc_TemHum> Dc_TemHum { get; set; }
        public virtual DbSet<Department> Departments { get; set; }
        public virtual DbSet<DoorOpening> DoorOpenings { get; set; }
        public virtual DbSet<Dormitory> Dormitories { get; set; }
        public virtual DbSet<DormitoryNum> DormitoryNums { get; set; }
        public virtual DbSet<Festival> Festivals { get; set; }
        public virtual DbSet<FireFacility> FireFacilities { get; set; }
        public virtual DbSet<FivePicture> FivePictures { get; set; }
        public virtual DbSet<Focuser> Focusers { get; set; }
        public virtual DbSet<Foreigner> Foreigners { get; set; }
        public virtual DbSet<ForeignerAppoint> ForeignerAppoints { get; set; }
        public virtual DbSet<ForeignerRecord> ForeignerRecords { get; set; }
        public virtual DbSet<GeneralLaboratory> GeneralLaboratories { get; set; }
        public virtual DbSet<GooutForm> GooutForms { get; set; }
        public virtual DbSet<HazardousChemicalsUseRecord> HazardousChemicalsUseRecords { get; set; }
        public virtual DbSet<HazardousChemicalsWarehouse> HazardousChemicalsWarehouses { get; set; }
        public virtual DbSet<InAndOutTime> InAndOutTimes { get; set; }
        public virtual DbSet<IncidentReport> IncidentReports { get; set; }
        public virtual DbSet<Library> Libraries { get; set; }
        public virtual DbSet<MainLab> MainLabs { get; set; }
        public virtual DbSet<Major> Majors { get; set; }
        public virtual DbSet<MapIcon> MapIcons { get; set; }
        public virtual DbSet<Monitor> Monitors { get; set; }
        public virtual DbSet<RecyclingManagement> RecyclingManagements { get; set; }
        public virtual DbSet<ResearchBuilding> ResearchBuildings { get; set; }
        public virtual DbSet<SafeManagement> SafeManagements { get; set; }
        public virtual DbSet<SchoolDistrict> SchoolDistricts { get; set; }
        public virtual DbSet<SchoolInCar> SchoolInCars { get; set; }
        public virtual DbSet<SchoolStaffRecord> SchoolStaffRecords { get; set; }
        public virtual DbSet<ScoreAdd> ScoreAdds { get; set; }
        public virtual DbSet<SecurityType> SecurityTypes { get; set; }
        public virtual DbSet<Specific> Specifics { get; set; }
        public virtual DbSet<Stadium> Stadia { get; set; }
        public virtual DbSet<StrangeWarning> StrangeWarnings { get; set; }
        public virtual DbSet<StuClass> StuClasses { get; set; }
        public virtual DbSet<Student> Students { get; set; }
        public virtual DbSet<StudentsApartment> StudentsApartments { get; set; }
        public virtual DbSet<StuManagement> StuManagements { get; set; }
        public virtual DbSet<StuMapCurriculum> StuMapCurriculums { get; set; }
        public virtual DbSet<sys_ApparatusRegistration> sys_ApparatusRegistration { get; set; }
        public virtual DbSet<sys_BlackList> sys_BlackList { get; set; }
        public virtual DbSet<sys_Captial> sys_Captial { get; set; }
        public virtual DbSet<sys_ConsumptionRecord> sys_ConsumptionRecord { get; set; }
        public virtual DbSet<sys_EntramceGuard> sys_EntramceGuard { get; set; }
        public virtual DbSet<sys_InsOpen> sys_InsOpen { get; set; }
        public virtual DbSet<sys_Instrument> sys_Instrument { get; set; }
        public virtual DbSet<sys_InstrumentFault> sys_InstrumentFault { get; set; }
        public virtual DbSet<sys_InstrumentMaintain> sys_InstrumentMaintain { get; set; }
        public virtual DbSet<sys_InstrumentUse> sys_InstrumentUse { get; set; }
        public virtual DbSet<sys_Laboratory> sys_Laboratory { get; set; }
        public virtual DbSet<sys_LaboratoryLog> sys_LaboratoryLog { get; set; }
        public virtual DbSet<sys_LaboratoryType> sys_LaboratoryType { get; set; }
        public virtual DbSet<sys_RechargeRecord> sys_RechargeRecord { get; set; }
        public virtual DbSet<sys_User> sys_User { get; set; }
        public virtual DbSet<SystemIcon> SystemIcons { get; set; }
        public virtual DbSet<SystemLog> SystemLogs { get; set; }
        public virtual DbSet<SystemMenu> SystemMenus { get; set; }
        public virtual DbSet<SystemPermission> SystemPermissions { get; set; }
        public virtual DbSet<SystemRole> SystemRoles { get; set; }
        public virtual DbSet<SystemRolePermissionMapping> SystemRolePermissionMappings { get; set; }
        public virtual DbSet<SystemUser> SystemUsers { get; set; }
        public virtual DbSet<SystemUserRoleMapping> SystemUserRoleMappings { get; set; }
        public virtual DbSet<Teacher> Teachers { get; set; }
        public virtual DbSet<Warning> Warnings { get; set; }
        public virtual DbSet<Weekly> Weeklies { get; set; }
        public virtual DbSet<whp_EntramceGuard> whp_EntramceGuard { get; set; }
        public virtual DbSet<Worker> Workers { get; set; }
        public virtual DbSet<Wrj> Wrjs { get; set; }
        public virtual DbSet<sys_InstrumentType> sys_InstrumentType { get; set; }
    }
}
